[package]
name = "evm-transaction-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
dotenv = "0.15.0"
env_logger = "0.10.0"
eyre = "0.6.8"
tokio = { version = "1.22.0", features = ["macros"] }
web3 = "0.18.0"
